### ISSUE TITLE
Inconsistencies/problems in LL or CMU API spec

### ISSUE THREAD

**Issue by ivoysey** [schmerl/LLStaging#14]
- [x] the table under "What are the possible states of your DAS? Fill in the table below, replacing the examples with information about your particular system" refers to old constants
- [x] the list under "An example test runs are:" refers to old end points
- [ ] the "functions used in automaton" refers to old end points, under CP2
- [ ] the listing "Test Automation" refers to old end points

**Comment by ivoysey** [comment]
- [ ] we say "ARGUMENTS" not "RESULT" in the returned JSON objects
- [ ] we don't define "VOLTAGE" anywhere
- [ ] action/observe contains metasyntax, "INSERT OTHERS HERE"

**Comment by ivoysey** [comment]
- [ ] the syntax for sensor perturbation for the config file in the wiki page includes two fields named "y"

**Comment by ivoysey** [comment]
- [ ] we should say that waypoint IDs are unique per map

**Comment by joshsunshine** [comment]
Slide 28 of the LL API Spec refers to ADAPTATION_INITIATED but that doesn't appear anywhere else in the document. 

> This event should only be reported after an ADAPTATION_INITIATED event and should only be reported once for each ADAPTATION_INITIATED event"

**Comment by joshsunshine** [comment]
remove references to endpoints and constants from API v0.7 from wiki page

**Comment by joshsunshine** [comment]
Slide 39 of LL API Spec says DAS should terminate if there is a problem accessing the log file. This is the only place it says DAS should terminate. Why don't we have to terminate in response to other error types?
>If the log file cannot be created, accessed, or written to, the DAS must send a Test Control Message of DAS_ERROR with an ERROR field value of DAS_LOG_FILE_ERROR and then terminate

**Comment by ivoysey** [comment]
in "Platform CP Parameter Description" on the wiki we spell out "pitch" "yaw" and "roll" instead of calling them p w and r as in the start up file. we should be consistent on this, and also mention somewhere the mapping between the short and long versions.

**Comment by joshsunshine** [comment]
Are the ranges for sensorPose inclusive or exclusive?

**Comment by schmerl** [comment]
Inclusive. Though konrad has said there is no guarantee that they won't try parameters out of the range.

**Comment by ivoysey** [comment]
OK. I do check for things out of range and post a DAS Error, so they can
check the out of range things as much as he wants.

So on the wiki right now we say things like `range(-3,3)` which is a little
ambiguous. The standard mathematical notation might be `[-3,3]` for
intervals contains their end points. We should probably either give a
comment about inclusiveness in that wiki page or switch to math notation.


---Ian

**Comment by schmerl** [comment]
For the ranges, this is Haskell. Does it have [-3,3]?

**Comment by ivoysey** [comment]
haskell ranges are more about lists and list type classes, i believe. so
that's a weird place to use that syntax if these things are floats.


---Ian

**Comment by schmerl** [comment]
Fixed everything except:

- [ ]  the "functions used in automaton" refers to old end points, under CP2
- [ ]  the listing "Test Automation" refers to old end points

**Comment by schmerl** [comment]
They're not floats. I've added a comment to the preamble to say the ranges are inclusive.

**Comment by schmerl** [comment]
Done.
