### ISSUE TITLE
estimating the deadline

### ISSUE THREAD

**Issue by ivoysey** [schmerl/LLStaging#16]

**Comment by schmerl** [comment]
Interestingly, the time (in seconds) that the path will take is now in the waypoints json file. You should be able to add that value to "now" when they call start to calculate the deadline.

**Comment by ivoysey** [comment]
So that's static, right? That means that we don't know the deadline until the hit start, but as soon as they hit start we know the deadline and never update it?

Does this mean that the spec on our wiki page for observe should have a default value for that field incase they observe before start?
