### ISSUE TITLE
inconsistencies in waypoint numbers

### ISSUE THREAD

**Issue by ivoysey** [schmerl/LLStaging#17]
coodinates in the IG files and waypoint_location json files are slightly different for the same waypoints. josh and i don't really know why this would be the case, but it's somewhat worrying. we'd like to be able to do string comparison rather than numerical comparison for the float values, but the float values differ between the two files.

**Comment by joshsunshine** [comment]
The map.json file you sent to lincoln labs and the coordinates in all of the instruction graph files.

**Comment by joshsunshine** [comment]
For example, ls_to_l7.ig contains: 
>P(V(1, do MoveAbs(52.2, 69.0, 1.0) then 2),
>V(2, do MoveAbs(42.5, 69.0, 1.0) then 3)::
>V(3, do MoveAbs(19.8, 69.0, 1.0) then 4)::
>V(4, do MoveAbs(19.8, 64.9, 1.0) then 5)::
>V(5, do MoveAbs(19.8, 58.7, 1.0) then 6)::
>V(6, end)::
>nil)
but the coordinates in instruction 4 and 5 above are slightly off from the coordinates in map_data.json
