### ISSUE TITLE
make sure gazebo won't move the robot after the battery dies

### ISSUE THREAD

**Issue by ivoysey** [schmerl/LLStaging#25]

**Comment by schmerl** [comment]
Can send a motor_power msg to /mobile_base/command/motor_power, e.g.:

rostopic pub /mobile_base/commands/motor_power kobuki_msgs/MotorPower '{state: 0}'

**Comment by ivoysey** [comment]
What's the semantics of that, inside ROS? Does it just tell that motor to never run again?

**Comment by schmerl** [comment]
It tells it to ignore any commands to the wheels.

**Comment by ivoysey** [comment]
OK, yeah, and that's sufficient because we're only being judged on things
that are visible through observe, like position and timeliness. So even if
commands keep getting sent, they won't have any effect on anything that's
included in the evaluation. Got it.


---Ian

**Comment by ivoysey** [comment]
cyrus's energy monitor sends "OFF" to the kobuki motor power topic when the battery hits zero, and indeed that is how brasscomms knows that the battery has hit zero. that should resolve this issue since it's the thing suggested above.
