### ISSUE TITLE
ignoring `rosparam`

### ISSUE THREAD

**Issue by ivoysey** [schmerl/LLStaging#31]
the output of running the simulation includes:
```
WARN: unrecognized 'rosparam' tag in <include> tag
```
grepping through the code base, that only appears once:
```
iev@iev-mbp installation % find . -type f | xargs grep --color=auto 'rosparam'       
./catkin_ws/src/cp_gazebo/launch/cp1.launch:    <rosparam file="$(find cp_gazebo)/global_costmap.yaml" command="load" ns="global_costmap"/>
iev@iev-mbp installation %
```
which sugguests to me that the global costmap isn't being loaded

**Comment by ivoysey** [comment]
This was definitely being ignored. It's nested inside of an `<include>` tag, I believe incorrectly. When I permute the two lines, so that the include ends before the `<rosparam>` tag starts, I get this in the output:
```
error loading <rosparam> tag: 
	file does not exist [/home/vagrant/catkin_ws/src/cp_gazebo/global_costmap.yaml]
XML is <rosparam command="load" file="$(find cp_gazebo)/global_costmap.yaml" ns="global_costmap"/>
The traceback for the exception was written to the log file
```

**Comment by schmerl** [comment]
I think we can get rid of it. It leaked in from something I was trying out.
