### ISSUE TITLE
Work out a way to scale the power model to work better for CP1

### ISSUE THREAD

**Issue by schmerl** [schmerl/LLStaging#38]

**Comment by schmerl** [comment]
It seems that a factor of 10 works fine, but this should come out in testing.

**Comment by bisc** [comment]
My only concern is using a consistent factor for charging and discharging, in adaptation and simulation.

**Comment by schmerl** [comment]
Factor of 10 used in simulator and rainbow. Caused us to switch to sim time. (Thanks Ivan :-( )
