### ISSUE TITLE
Add instructions to instruction graph

### ISSUE THREAD

**Issue by schmerl** [schmerl/LLStaging#42]
Need to add the following instructions to the instruction graph code to send to the robot:

- recharge
- reconfigure (turn off kinect, change amcl params)
- recalibarate..? <-- This could be an effector only

**Comment by schmerl** [comment]
Recharge(15.00) - means recharge for n seconds?

**Comment by javier-camara** [comment]
Yes, that's right.

**Comment by javier-camara** [comment]
This is working now. See below a sample translation (the last four actions were artificially added to the plan, just to see how translation worked, but they don't actually make any sense as a plan).

P(V(1, do MoveAbs(52.2, 69.0, 0.35) then 2),
V(2, do MoveAbs(42.5, 69.0, 0.35) then 3)::
V(3, do MoveAbs(31.1, 69.0, 0.35) then 4)::
V(4, do Recharge(15.00) then 5)::
V(5, do Recharge(15.00) then 6)::
V(6, do MoveAbs(19.8, 69.0, 0.35) then 7)::
V(7, do MoveAbs(14.8, 69.0, 0.68) then 8)::
V(8, do SetLocalizationFidelity(0) then 9)::
V(9, do SetLocalizationFidelity(1) then 10)::
V(10, do SetLocalizationFidelity(2) then 11)::
V(11, do Recalibrate() then 12)::
V(12, end)::
nil)

**Comment by schmerl** [comment]
2 here is high? Can you remind me of the values needed in the high and medium case?

**Comment by javier-camara** [comment]
Yes, 2 is high. To summarize:
 * hi (2) -> Sets kinect on, AMCL configuration: 'kinect_array 550, update_min_a 0.0, update_min_d 0.2' (rest of parameters default).

  *  med (1) ->Sets kinect on, AMCL configuration: 'kinect_array 640, update_min_a PI/6, update_min_d 0.6' (rest of parameters default). 

  * lo (0) -> Sets kinect off - no parameters to set on AMCL.

**Comment by schmerl** [comment]
One thing. Recalibrate should take one integer parameter (whether to do the fast version - 0 - or the slow version - 1)

**Comment by schmerl** [comment]
I do not see a kinect_array parameter in ACML. Am I looking in the right place?

This is what I see:
![image](https://cloud.githubusercontent.com/assets/4161280/23385238/bb233080-fd1c-11e6-8c80-a0a61bd87c3b.png)
![image](https://cloud.githubusercontent.com/assets/4161280/23385249/c878c4ac-fd1c-11e6-881b-a5293bf81eac.png)

**Comment by javier-camara** [comment]
Been talking to Pooyan, and apparently, kinect_array is not a parameter of AMCL. He's talking to Miguel to find out more about this.

Working in the addition to recalibrate.

**Comment by javier-camara** [comment]
Modified IG translation to go from MoveAbs to MoveAbsH (including desired heading after robot moves)

**Comment by javier-camara** [comment]
Adding instruction relocate after going back to kinect on to the IG translation. What are the parameters expected for relocate: waypoint label, map coordinates, or something else?

**Comment by javier-camara** [comment]
I think this one is done. Closing.
