### ISSUE TITLE
Converter for new instructions

### ISSUE THREAD

**Issue by schmerl** [schmerl/LLStaging#45]
The new instructions in the PRISM plan need to be translated into instructions/effectors in Rainbow.  The steps are:

1. Resolve what instructions are necessary
2. Decide whether they go into the instruction graph, or are just done as separate effectors
3. Implement whatever we decide in 2

**Comment by javier-camara** [comment]
I am not sure I understand what the difference is between this and #42.

**Comment by schmerl** [comment]
#42 is related - it's to do with instruction graphs. This is to do with the planner/executor.

**Comment by javier-camara** [comment]
OK, got it. I am working through the full integration of these instructions in the planner.

**Comment by javier-camara** [comment]
The new tactics for CP1 are fully integrated in the planner now (including impacts on energy consumption, etc).
