### ISSUE TITLE
CP2: Make sure delta calibration files are copied (all 16000 of them)

### ISSUE THREAD

**Issue by schmerl** [schmerl/LLStaging#55]
Question: for git, is it better to zip all these files up to check them in, and then unzip them as part of vagrant, or just check them in bare.

Also need to test that calibration_watcher can find them

**Comment by schmerl** [comment]
Awesomely, the DeltaCalibration git repository has 104,316 files, which takes a long time to check out. 

It now has 87,808 files and takes up ~400MB on disk.

**Comment by schmerl** [comment]
These files will not change.

**Comment by ivoysey** [comment]
My _guess_ is that committing a zip (to LFS?) and unzipping it on provision will be faster -- per our discussion comparing it to tar-then-scp vs. scp-then-tar. If they aren't going to change then that seems like the right thing to do, or at least to try with a fallback.
