### ISSUE TITLE
CP2: Calibration_watcher

### ISSUE THREAD

**Issue by schmerl** [schmerl/LLStaging#56]
Calibration_watcher, in /home/vagrant/bin needs to be started in start.sh when CP2_Adaptation is in effect. Because it is resource hungry, we need to be a bit careful how to start this up. Starting it up concurrently with other things (especially when startup has a flurry of messaging), could cause messages to get lost and screw up (e.g.) Rainbow.

**Comment by ivoysey** [comment]
i'm going to start this up in brasscomms so that i can make sure it happens after gazebo comes up but before we send DAS_READY.
