### ISSUE TITLE
Voltage goes from 104 to 0 when battery completely discharges 

### ISSUE THREAD

**Issue by bisc** [schmerl/LLStaging#62]
Suspect: Cyrus's code
Detected by: @javier-camara  
Localized by: @ivoysey

**Comment by ivoysey** [comment]
this is a duplicate of https://github.com/cyrus-/brass-energy-monitor/issues/1

**Comment by ivoysey** [comment]
we don't think this will cause planning issues. so it's weird and we should fix it, but not today.

**Comment by bisc** [comment]
fixed an off-by-one bug in cyrus-/brass-energy-monitor.
